version: "3.8"
# -----------DB-------------
services:
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  content-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: content_db
    ports:
      - "5434:5432"
    volumes:
      - content-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d content_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  review-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: review_db
    ports:
      - "5435:5432"
    volumes:
      - review-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d review_db"]
      interval: 5s
      timeout: 3s
      retries: 5
  reservation-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reservation_db
    ports:
      - "5436:5432"
    volumes:
      - reservation-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d reservation_db"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  provider-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: provider_db
    ports:
      - "5437:5432"
    volumes:
      - provider-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d provider_db"]
      interval: 5s
      timeout: 3s
      retries: 5

# --------서비스--------
  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    env_file:
      - ./auth-service/.env
    depends_on:
      auth-db:
        condition: service_healthy

  content-service:
    build: ./content-service
    ports:
      - "8002:8000"
    env_file:
      - ./content-service/.env
    depends_on:
      content-db:
        condition: service_healthy

  review-service:
    build: ./review-service
    ports:
      - "8003:8000"
    env_file:
      - ./review-service/.env
    depends_on:
      review-db:
        condition: service_healthy

  reservation-service:
    build: ./reservation-service
    ports:
      - "8004:8000"
    env_file:
      - ./reservation-service/.env
    depends_on:
      reservation-db:
        condition: service_healthy

  provider-service:
    build: ./provider-service
    ports:
      - "8005:8000"
    env_file:
      - ./provider-service/.env
    depends_on:
      provider-db:
        condition: service_healthy

volumes:
  auth-db-data:
  content-db-data:
  review-db-data:
  reservation-db-data:
  provider-db-data: