version: "3.8"
# -----------DB 3종-------------
services:
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 3s
      retries: 5

  content-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: content_db
    ports:
      - "5434:5432"
    volumes:
      - content-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 3s
      retries: 5

  review-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: review_db
    ports:
      - "5435:5432"
    volumes:
      - review-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 3s
      retries: 5

# --------서비스 3종--------
  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@auth-db:5432/auth_db
      - SECRET_KEY=supersecret
    depends_on:
      auth-db:
        condition: service_healthy

  content-service:
    build: ./content-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@content-db:5432/content_db
    depends_on:
      content-db:
        condition: service_healthy

  review-service:
    build: ./review-service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@review-db:5432/review_db
    depends_on:
      review-db:
        condition: service_healthy

volumes:
  auth-db-data:
  content-db-data:
  review-db-data:
